###
#   Database Settings
###
spring:
  datasource:
    url: jdbc:h2:mem:user-app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    #url: jdbc:mariadb://localhost:3306/usermanager
    platform: h2
    # platform: mysql
    username: sa
    # username: root
    password:
    # password: root
    driverClassName: org.h2.Driver
    # driverClassName: org.mariadb.jdbc.Driver
    initialization-mode: never
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true

###
#   H2 Settings
###
  h2:
    console:
      enabled: false
      path: /console
      settings:
        trace: false
        web-allow-others: false
  pid:
    file: usermanager.pid
    fail-on-write-error: false



logging:
  level:
    ROOT: WARN
    sshd:
      shell: DEBUG
sshd:
  shell:
    password: admin
    enabled: true
    port: 2000

